### ISSUE TITLE
Recommended usage of shell integration

### ISSUE THREAD

**Issue by klauer** [conda-forge/fzf-feedstock#20]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Shell integration features from fzf are very handy, allowing for fuzzy finding of bash history, files in the local directory, and so on with just a keypress. On installation with homebrew, for example, a helpful message is output indicating how to enable the shell integration ([ref](https://formulae.brew.sh/api/formula/fzf.json))

It may be worth mentioning in the documentation that shell integration can be enabled by way of:

```bash
source $CONDA_PREFIX/share/fzf/shell/completion.bash
source $CONDA_PREFIX/share/fzf/shell/key-bindings.bash
```

It'd be neat to have this configured in a conda activation script, but I can understand why that might be considered a bad idea for the general case.

**Comment by izahn** [comment]
I don't know if there are shell integration conventions in the conda-forge community, but it would be great if this worked with less effort.

https://github.com/archlinux/svntogit-community/blob/packages/fzf/trunk/PKGBUILD is a good example of fzf packaging that includes integration for supported shells.

**Comment by dbast** [comment]
no need anymore to bundle files for that, as there e.g. is `eval "$(fzf --bash)"` see https://github.com/junegunn/fzf?tab=readme-ov-file#binary-releases
